services:
  - type: web
    name: api-for-be
    runtime: node
    plan: free
    branch: main
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DB_HOST
        value: mysql1002.site4now.net
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: ab9d81_sneaker
      - key: DB_PASS
        value: Sneaker0123
      - key: DB_NAME
        value: db_ab9d81_sneaker
      - key: URL_REACT
        value: http://localhost:3000
